---
title: "Untitled"
output: word_document
---

### Brisbane

Cecilia B. Fernández | Public Affairs Officer  
Australian Embassy Villanueva 1400 Buenos Aires, Argentina  

Estimada Cecilia B. Fernández,

Gracias por su correo electrónico del día 27 de febrero de 2019. Quisiera aprovechar su generosa oferta de AUD 2.000 para perfeccionamiento profesional. 

Soy un "Alumni" registrado en la Embajada de Australia en Argentina. Hice mi doctorado en la Universidad de Queensland, Australia (diploma: http://bit.ly/maurolepore_phd). Mi area de estudio fue ecologia, y desde entonces me especialice en programacion para el analisis de datos ecologicos. Quisiera asistir a un entrenamiento en habilidades de programacion y ciencia de datos apundato a investigadores. 

DETALLES

Los detalles del curso son estos:

Introduction to Python - Software Carpentry  
N53 0.57 Nathan Campus, Griffith University  
9am to 5pm 15th-17th April, 2019  
https://bio-swc-bne.github.io/2019-04-15-GriffithUni-Python/  

BENEFICIOS

Este curso tendra un impacto muy positivo en mi desarrollo profesional. Me dara herramientas nuevas, que me permitiran resolver un rango mas amplio de problemas de investigacion. Este curso esta enfocado en una lengua de programacion (Python) que he usado poco, y complementa muy bien mi amplia experiencia en un lengua de programacion similar (R). Ademas, Este curso me reconectara con Australia, particularmente con gente que trabaja en areas muy similares a la mia.

NOTAS

* El curso se desarrollara en aproximadamente dos semanas. Le agradeceria enormemente que procesara mi aplicacion lo antes posible.

* El curso es gratuito. Usare el presupuesto enteramente en viaje y estadia.

* Yo soy instructor de la organizacion que dicta este curso, y me ofreci a ayudar con una tecnologia que conozco muy bien (Git) porque aparentemente necesitan ayuda (https://twitter.com/hackyhourGU/status/1111052438855770112). Esto significa que, aun si mi nombre apareciera listado como instructor o ayudante, este entrenamiento me ensanhara a mi mucho mas de lo que yo ensenhare a otros.

Si tiene alguna duda, por favor no dude en contactarme.

Muy atentamente,  
Mauro Lepore  

IT Specialist - R package developer  
https://forestgeo.si.edu/mauro-lepore  
Smithsonian Institution, ForestGEO  
Washington DC, 20560, US  
Phone: +1 202 633 2204 | Mob. +1 346 773 2738  
maurolepore@gmail.com  



















### Announcement

Descubrimiento de conocimiento a partir de datos

Jueves 6 de mayo, 8:00AM - viernes 7 de mayo, 5PM

Este es un curso intensivo dedicado a científicos de datos con experiencia previa. Al final del curso, habrás aprendido las mejores prácticas y podrás aplicarlas para resolver problemas reales de negocios y ciencia.

Día 1

Primero revisaremos brevemente algunos conceptos y técnicas fundamentales. Luego discutiremos en grupo posibles soluciones a tres casos reales tratados en ixpantia. Finalmente revelaremos la solución de ixpantia en cada caso, resaltando la aplicación practica de los conceptos teóricos previamente mencionados, y mencionando que compromisos son comunes, necesarios, y aceptables en el contexto de negocios y ciencia.

 Día 2:

Elijaras un proyecto basado en datos y problemas reales de negocios y ciencia. Te acompañaremos en el proceso de búsqueda, limpieza, transformación, visualización, modelado, y comunicación de datos. Te guiaremos en la construcción de las herramientas necesarias para completar tu proyecto.



--------

> La solicitud deberá realizarse antes de fines de marzo mediante una carta de intención que detalle la actividad a realizar y su rol dentro de la misma.



Gracias por informarme sobre el programa de apoyo a exestudiantes y becarios de Universidades de Australia. 

Quisiera aprovechar su oferta de asistencia financiera para asistir a una capacitacion en Melbourne, Australia, del 13 al 15 de mayo de 2019 -- incluyendo un dia de workshop seguido de dos dias de conferencia. 

El costo seria proximadamente AUD 1.980, incluyendo la capacitacion (AUD 580 https://lambdajam.yowconference.com.au/register/) y vuelos (AUD 1.400 https://flights.app.goo.gl/xePUA). El presupuesto disponible seria insuficiente para cubrir la estadia, pero con mucho gusto la pagaria yo mismo.

Le recuerdo que registrado como "Alumni" en Argentina. Soy un exestudiante de la Universidad de Queensland, donde complete mi doctorado en 2015 (certificado obtenido: http://bit.ly/maurolepore_phd).

Y el anho pasado recibi su generoso apoyo para asistir a un workshop de desarrollo de software en Estados Unidos (http://bit.ly/2Ehs7mD). Ese curso me ayudo a mejorar la calidad y eficiencia de mi trabajo, y extendio mi red de contactos profesionales en el contexto de la lengua de programacion que mas utilizo (https://www.r-project.org/), principalmente en Estados Unidos.

Este anho su apoyo elevaria mis habilidades a un nivel mas general. La capacitacion que ahora propongo esta enfocada no en una lengua de programacion especifica sino en un paradigma general que abarca muchas lenguas de programacion (https://lambdajam.yowconference.com.au/). Ademas, esta capacitacion me llevaria a Australia por primera vez desde que termine mis estudios.



### Application

Cecilia B. Fernández | Public Affairs Officer
Australian Embassy Villanueva 1400 Buenos Aires, Argentina

Estimada Cecilia B. Fernández,

Gracias por su correo electrónico del día 27 de febrero de 2019. Soy un “Alumni” registrado en la Embajada de Australia en Argentina y quisiera aprovechar su generosa oferta de AUD 2.000 para perfeccionamiento profecional.


El anho (xxx) pasado recibi apoyo para el curso Building Tidy Tools. Este anho quisiera aprovechar nuevamente su generosa oferta para desarrollar mis habilidades profesionales aun mas.

xxx

Si tiene alguna duda, por favor no dude en contactarme.

Muy atentamente,
Mauro Lepore
IT Specialist - R package developer
https://forestgeo.si.edu/mauro-lepore
Smithsonian Institution, ForestGEO
Washington DC, 20560, US
Phone: +1 202 633 2204 | Mob. +1 346 773 2738
maurolepore@gmail.com







Mis estudios en Australia están vinculados con mi trabajo actual de la siguiente forma. En Australia -- como parte de mis estudios doctorales -- aprendí a desarrollar programas para el análisis de datos ecológicos; y me gradué como “Doctor of Philosophy” de la Universidad de Queensland, Australia en noviembre del 2015 (diploma: http://bit.ly/maurolepore_phd). Mis habilidades y título nuevos derivaron en una investigación post-doctoral en el “Smithsonian Tropical Research Institute”, y son fundamentales para mi trabajo actual en ForestGEO. ForestGEO es una red internacional de investigadores de bosques (https://forestgeo.si.edu). Mi trabajo consiste en desarrollar programas para esos investigadores puedan analizar sus datos eficientemente (biografía profesional: https://bit.ly/mauro-lepore).

Con su apoyo económico quisiera registrarme en un curso que impactaría positivamente en mi trabajo, ahora y en el futuro. El curso es un entrenamiento intensivo para desarrollar mejores programas para el análisis de datos (curso: http://bit.ly/2Ehs7mD). (El curso cuesta un poco mas que AUD 2.000 pero yo pagaría la diferencia). El instructor es Hadley Wickham (http://hadley.nz/) -- uno de los referentes mundiales en el área, y es quien creo el paradigma de programación que yo utilizo para desarrollar mis propios programas. El curso tendría, entre otros, estos beneficios:
•	Aumentaría mi productividad: Me ayudaría a reducir el tiempo que necesito para desarrollar nuevos programas para el análisis de datos.
•	Aumentaría la calidad de mi trabajo: Me ayudaría a desarrollar programas que son más fáciles de entender, modificar, y utilizar.
•	Extendería mi red de contactos profesionales: Me permitiría conocer personalmente a expertos en mi área.



