---
title: "elife profile"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  comment = "#>",
  error = TRUE,
  collapse = TRUE
)
```

### Name

First name
Mauro
Last name
Lepore

### Job title, Organisation (optional)

Software developer (2degrees-investing.org).

Sometimes:

* Consultant (ixpantia.com).
* Data science instructor (carpentries.org).
* Active in the R community (e.g. rOpenSci , RLadies).

### Put in a profile pic

Dropbox/Temp/images_common

### Interests?

* Learning and teaching.
* Using and building and systematic solutions.
* Predicting human (i)rationality.

How?

* Pragmatic (sensible, realistic, practical).
* Inclusive (affordable, diverse, fun).
* Collaborative (open, transparent).
* Scalable (reproducible, reusable, maintainable).

Contribute?

* Software development (R packages).
* Version control (Git + GitHub).
* Continuous integration (TravisCI).

ask/need?

Goal: Can we create a system to more easily and effectively onboard new commers to open science/research?

* People who want both to improve something and have fun doing it (__growth and kindness mindset__). By donating our time we are all making a favour to each other. How would you communicate with someone who is doing a favour to you?

* People with experience in __design thinking__ (building/testing prototype)

* People to __research__ on potential approaches (Carpentries, rOpenSci, Greg Wilson).
  * What are the elements of a successfull onboarding process?
      * Community? People with experience/interest __building community__.
      * Elegance? People with experience/interest in __editting__ or giving constructive __peer-review__.
      * Free? People with experience/interest in __open source__.

* Maybe people to develop and answer a survey.
