---
title: "2019, eLife (Cambridge, UK): Application"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

https://sprint.elifesciences.org/

### Call for projects. 

> Do you have a project/idea that you would like to develop at the Sprint? By applying to be a project lead, you will have the opportunity to pitch your project before the Sprint. Please note that we would like to support projects that are still in their infancies/beta stages. At the Innovation Sprint, I would like to work on...

> Please tell us briefly which problem(s) you would like to address in relation to research communication, open science, and/or applying the latest technologies to research and discovery.

At the Innovation Sprint, I would like create a minimal kit of learning resources and tools for researchers to more easily build the skills and infrastructure they need to contribute to open science.

### Your skills and experience. 

> Please specify other skills of relevance that you would share at the event, or add detail to explain any of the skills listed above, such as specifying programming languages, technical skills, area of research, and listing years of experience. Include any relevant links, such as your website and/or Twitter, Github and/or LinkedIn pages.

I am an ecologist turned software developer and data science trainer and consultant (https://www.linkedin.com/in/mauro-lepore/). My mission is to help scientists work openly and collaboratively. 

At the event I would like to share my experience teaching and building software infrastructure to help researchers work in a way that is more open, reproducible, and fun. I have already helped a few research groups globally, but with your help we could build a system that scales up well and has a massive positive impact on open science.

I started using R over five years ago, during my PhD (UQ, Australia) and continued during my postdoc (Smithsonian; Panama). Since 2017 I build R packages for a global network of forest ecologists (Smithsonian, USA; https://forestgeo.github.io/fgeo/). Technologies I use daily include R, RStudio, Git, GitHub, and TravisCI. I am also a data science trainer for The Carpentries (https://carpentries.org/), and a freelance consultant for ixpantia (https://ixpantia.com).

I regularly contribute to open software and reproducible research (https://maurolepore.github.io). For example, I am an instructor for The Carpentries (https://carpentries.org/instructors/), and a peer-reviewer of rOpenSci packages (http://bit.ly/mauro-ropensci-review-gitignore). Also, I have been invited to attend other open science meetings (https://unconf18.ropensci.org/#participants, and https://chirunconf.github.io/#team), and to speak at a DataLatam webinar (http://youtu.be/SVzyWV1Iep8).

### I am interested in participating in the Innovation Sprint because…

> Please tell us briefly what you hope to gain from participating in the event.

I am interested in participating in the Innovation Sprint because with the help of other motivated attendees we could build a scalable system for on-boarding researchers into data science.

Many of us (attendees) already have some experience on-boarding fellow researchers who want to work in a more open, collaborative, and reproducible way. Many attempts may have failed but some surely worked. Collectively, we should have enough success stories to identify what works and why, then focus on building a system to replicate those "bright spots" at scale. Two models that we could use for inspiration are rOpenSci and The Carpentries.

### Tell us about something you have created that you are proud of:

> Please share the story of an idea you have prototyped or brought to fruition before, what you contributed and learned, and why you are proud of this. The idea does not need to relate to the scope of this event, but we are particularly interested in contributions to any open (source or science) projects!

In less than two years I went from building my first R package to building a package-ecosystem for a global network of forest ecologists (https://forestgeo.github.io/fgeo/). Along the way, I met some of the most productive and friendly R developers worldwide, and joined multiple meetups and organizations supporting open science. Inspired, I learned the best practices in software development with R. I am proud that I am now able to give back to the open software/data community by teaching others what I now know.

### Have you been or are you currently involved with eLife?

> Please list any associations with eLife, such as being a participant at last year's Sprint, an eLife Ambassador or ECAG member, involvement in a project or initiative supported by eLife, or having worked directly with us before. We may take this into account when selecting between highly rated applications; other factors are of higher priority.

No.

---

Proposing a project: 

### Please describe the project/idea you would like to pursue at the Sprint. Please tell us about the motivation behind the idea, what you hope to achieve at the Sprint, and what skill sets you are looking for in your team. Feel free to include any relevant links to Github repositories/websites.

Smart, motivated researchers shouldn't struggle to join the open science revolution. At the Sprint I hope to develop a scalable system to on-board researchers who want to work in a more transparent, reproducible, and collaborative way. Two models for inspiration include rOpenSci (https://ropensci.org) and The Carpentries (https://carpentries.org/).

The Sprint should gather researchers representing a wide range of fields and computational ability. This is an excellent opportunity to prototype and test a kit with the minimal learning resources and tools for new open scientists to build their own skills and software infrastructure. 

The system may include:

* Fast, friendly support from previously on-boarded researchers (e.g. via slack).
* A simple way to incorporate feedback (e.g. via Google forms or GitHub issues). 
* Tutorials of multiple kinds (e.g. interactive, text, video).
* A checkout process to credit newly on-boarded folks (e.g. certificate, badge).
* A strong focus on community, diversity, respect, continuous learning.
* A code of conduct.
* A way to make people feel safe asking questions.
* A way to make people feel good about answering questions.

Useful technologies and learning resources are already available, but they are so many, scattered, and full of jargon that most researchers end up frustrated and paralyzed. 

As a data science instructor, developer and consultant, time and again I have seen researchers give up during the steep initial learning curve, before they experience the payoff. It is not them who fail; the failure is of the system that filters who joins the open science club. A lot of people want to join but the club is too exclusive. Let's make open science a popular club. Can we make open science the path of least resistance and the most fun?

